/**
 * Coupon scheduling — client-side orchestration for materializing a bond's
 * upcoming coupon (and final premium) via POST /api/dividends.
 *
 * Design:
 * The POST handler cleans up any previously materialized upcoming coupon and
 * recreates it with a deterministic ID, so scheduleNextCoupon is a safe UPSERT.
 * It is called from three places that must all behave identically:
 *   1. AssetDialog, right after a bond is created/updated;
 *   2. InflationRateDialog, after the user announces an inflation rate;
 *   3. (indirectly) the daily cron mirrors this logic server-side in dividendProcessor.
 *
 * The actual coupon math + note live in the pure layer (resolveCoupon /
 * buildCouponNote in couponUtils) so the client and the cron stay in lockstep.
 *
 * Non-critical by contract: a failure here never rolls back the asset save —
 * callers wrap the call and surface a soft error.
 */

import { authenticatedFetch } from '@/lib/utils/authFetch';
import { toDate } from '@/lib/utils/dateHelpers';
import { buildCouponNote, getNextCouponDate, resolveCoupon } from '@/lib/utils/couponUtils';
import { BondDetails } from '@/types/assets';

export interface ScheduleCouponParams {
  assetId: string;
  bondDetails: BondDetails;
  quantity: number;
  currency: string;
  taxRate?: number;
  userId: string;
}

export interface ScheduleNextCouponResult {
  scheduled: boolean;
  date?: Date;
  isProvisional?: boolean;
}

/**
 * Resolves the coupon tax rate: the asset's own rate when set (e.g. 12.5% for
 * BTPs), otherwise the Italian default of 26%.
 */
function resolveCouponTaxRate(taxRate?: number): number {
  return taxRate && !isNaN(taxRate) && taxRate > 0 ? taxRate : 26;
}

/**
 * Materializes (upserts) the next upcoming coupon for a bond.
 *
 * For inflation-linked bonds whose FOI rate for the period has not yet been
 * announced, the coupon is provisional (fixed floor) — see resolveCoupon.
 *
 * @returns the scheduled date and whether the coupon is provisional, or
 *          { scheduled: false } when the bond has no further coupon (matured).
 */
export async function scheduleNextCoupon(params: ScheduleCouponParams): Promise<ScheduleNextCouponResult> {
  const { assetId, bondDetails, quantity, currency, taxRate, userId } = params;

  const issueDate = toDate(bondDetails.issueDate);
  const maturityDate = toDate(bondDetails.maturityDate);
  const nominalValue = bondDetails.nominalValue ?? 1;
  const effectiveTaxRate = resolveCouponTaxRate(taxRate);

  const nextDate = getNextCouponDate(issueDate, bondDetails.couponFrequency, maturityDate);
  if (!nextDate) return { scheduled: false };

  const resolved = resolveCoupon(nextDate, bondDetails, nominalValue);
  const gross = resolved.perShare * quantity;
  const tax = gross * (effectiveTaxRate / 100);

  const response = await authenticatedFetch('/api/dividends', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      userId,
      dividendData: {
        assetId,
        exDate: nextDate,
        paymentDate: nextDate,
        dividendPerShare: resolved.perShare,
        quantity,
        grossAmount: gross,
        taxAmount: tax,
        netAmount: gross - tax,
        currency,
        dividendType: 'coupon',
        isAutoGenerated: true,
        isProvisional: resolved.isProvisional,
        notes: buildCouponNote(resolved, bondDetails.couponFrequency),
      },
    }),
  });

  return { scheduled: response.ok, date: nextDate, isProvisional: resolved.isProvisional };
}

/**
 * Materializes (upserts) the final loyalty premium paid at maturity, if the bond
 * defines one and has not yet matured. No-op otherwise.
 */
export async function scheduleFinalPremium(params: ScheduleCouponParams): Promise<boolean> {
  const { assetId, bondDetails, quantity, currency, taxRate, userId } = params;

  if (!bondDetails.finalPremiumRate) return false;
  const maturityDate = toDate(bondDetails.maturityDate);
  if (maturityDate <= new Date()) return false;

  const nominalValue = bondDetails.nominalValue ?? 1;
  const effectiveTaxRate = resolveCouponTaxRate(taxRate);
  const premiumPerShare = (bondDetails.finalPremiumRate / 100) * nominalValue;
  const premiumGross = premiumPerShare * quantity;
  const premiumTax = premiumGross * (effectiveTaxRate / 100);

  const response = await authenticatedFetch('/api/dividends', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      userId,
      dividendData: {
        assetId,
        exDate: maturityDate,
        paymentDate: maturityDate,
        dividendPerShare: premiumPerShare,
        quantity,
        grossAmount: premiumGross,
        taxAmount: premiumTax,
        netAmount: premiumGross - premiumTax,
        currency,
        dividendType: 'finalPremium',
        isAutoGenerated: true,
        notes: `Premio finale a scadenza — ${bondDetails.finalPremiumRate}%`,
      },
    }),
  });

  return response.ok;
}
