import 'server-only';
import { z } from 'zod';
import { NextResponse } from 'next/server';

/**
 * Server-side input validation schemas (SEC-3).
 *
 * These schemas are the authoritative runtime gate for untrusted data arriving
 * at API boundaries. Client-side Zod schemas in forms are a UX convenience only
 * — they can be bypassed by writing directly to Firestore or crafting raw HTTP
 * requests. Validate here regardless of what the client-side already checked.
 *
 * WARNING: If you add a new schema for a sensitive field, also apply it at every
 * call site (route handler AND service layer for inputs that originate from
 * Firestore rather than the HTTP request).
 */

/** ISIN: 2 country letters + 9 alphanumeric + 1 check digit. */
export const isinSchema = z
  .string()
  .regex(/^[A-Z]{2}[A-Z0-9]{9}[0-9]$/, 'Invalid ISIN format');

/** Yahoo Finance ticker: letters, digits, and the symbols Yahoo uses (., -, ^, =). */
export const tickerSchema = z
  .string()
  .min(1)
  .max(20)
  .regex(/^[A-Za-z0-9.^=\-]+$/, 'Invalid ticker format');

export const snapshotRequestSchema = z.object({
  userId: z.string().min(1),
  year: z.number().int().min(2000).max(2100).optional(),
  month: z.number().int().min(1).max(12).optional(),
  cronSecret: z.string().optional(),
});

/** Covers the server-relevant subset of DividendFormData fields. */
export const dividendDataSchema = z.object({
  assetId: z.string().min(1),
  // Dates arrive as ISO strings in JSON; coerce to Date objects.
  exDate: z.coerce.date(),
  paymentDate: z.coerce.date(),
  dividendPerShare: z.number().finite(),
  quantity: z.number().finite(),
  grossAmount: z.number().finite(),
  taxAmount: z.number().finite(),
  netAmount: z.number().finite(),
  currency: z.string().min(1).max(10),
  dividendType: z.enum([
    'ordinary',
    'extraordinary',
    'interim',
    'final',
    'coupon',
    'finalPremium',
  ]),
  notes: z.string().optional(),
  isAutoGenerated: z.boolean(),
  // Inflation-linked provisional coupon flag (fixed-only, awaiting the announced FOI rate).
  isProvisional: z.boolean().optional(),
  // Optional ISIN present on some dividend payloads (bond coupons); validate if provided.
  assetIsin: isinSchema.optional(),
  // Server-set cost basis snapshot — validated if present in the payload.
  costPerShare: z.number().finite().optional(),
});

/**
 * Asset trade-ledger schemas (Registro operazioni asset — see
 * docs/specs/1-asset-transactions/01-data-model-and-rules.md §4).
 *
 * These are the HTTP-boundary gate. Semantic checks that need Firestore data (asset exists and is
 * a ledger type, date >= baselineDate, linked asset is `cash`, no-negative-position replay) live in
 * the use-case layer, NOT here — see docs/specs/1-asset-transactions/03-service-and-api.md.
 */
export const assetTransactionTypeSchema = z.enum(['buy', 'sell', 'adjustment']);

/**
 * Base object shape, without cross-field refinements. Extracted so the update schema can build on
 * it with `.partial()`/`.omit()`: those methods live on ZodObject, and adding a `.superRefine()`
 * turns the schema into a ZodEffects that no longer exposes them.
 */
const assetTransactionBaseSchema = z.object({
  assetId: z.string().min(1),
  type: assetTransactionTypeSchema,
  // Dates arrive as ISO strings in JSON; coerce to Date objects.
  date: z.coerce.date(),
  quantity: z.number().finite().min(0),
  pricePerUnit: z.number().finite().min(0),
  fees: z.number().finite().min(0).optional(),
  linkedCashAssetId: z.string().min(1).optional(),
  note: z.string().max(500).optional(),
});

/** Cross-field rules shared by create and update. `type`/`quantity` may be absent on an update. */
function refineAssetTransaction(
  data: { type?: 'buy' | 'sell' | 'adjustment'; quantity?: number; fees?: number; linkedCashAssetId?: string },
  ctx: z.RefinementCtx
): void {
  // buy/sell need a strictly positive quantity; adjustment allows 0 (position-close correction).
  if (data.type !== undefined && data.type !== 'adjustment' && data.quantity !== undefined && data.quantity <= 0) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['quantity'],
      message: 'La quantità deve essere maggiore di zero per acquisti e vendite.',
    });
  }
  // An absolute reset moves no money: fees and a linked cash settlement make no sense on it.
  if (data.type === 'adjustment' && data.fees !== undefined) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['fees'],
      message: 'Una rettifica non prevede commissioni.',
    });
  }
  if (data.type === 'adjustment' && data.linkedCashAssetId !== undefined) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['linkedCashAssetId'],
      message: 'Una rettifica non movimenta liquidità.',
    });
  }
}

export const assetTransactionDataSchema = assetTransactionBaseSchema.superRefine(refineAssetTransaction);

/** PUT payload: every field optional, and a trade can never be moved to another asset. */
export const assetTransactionUpdateSchema = assetTransactionBaseSchema
  .omit({ assetId: true })
  .partial()
  .superRefine(refineAssetTransaction);

/**
 * Parse helper: runs safeParse and returns either the typed data or a
 * ready-to-return 400 NextResponse with flattened zod error details.
 */
export function parseOr400<T>(
  schema: z.ZodType<T>,
  data: unknown
): { ok: true; data: T } | { ok: false; response: NextResponse } {
  const result = schema.safeParse(data);
  if (result.success) {
    return { ok: true, data: result.data };
  }
  return {
    ok: false,
    response: NextResponse.json(
      { error: 'Invalid request', details: result.error.flatten() },
      { status: 400 }
    ),
  };
}
