import 'server-only';
import { z } from 'zod';
import { NextResponse } from 'next/server';

/**
 * Server-side input validation schemas (SEC-3).
 *
 * These schemas are the authoritative runtime gate for untrusted data arriving
 * at API boundaries. Client-side Zod schemas in forms are a UX convenience only
 * — they can be bypassed by writing directly to Firestore or crafting raw HTTP
 * requests. Validate here regardless of what the client-side already checked.
 *
 * WARNING: If you add a new schema for a sensitive field, also apply it at every
 * call site (route handler AND service layer for inputs that originate from
 * Firestore rather than the HTTP request).
 */

/** ISIN: 2 country letters + 9 alphanumeric + 1 check digit. */
export const isinSchema = z
  .string()
  .regex(/^[A-Z]{2}[A-Z0-9]{9}[0-9]$/, 'Invalid ISIN format');

/** Yahoo Finance ticker: letters, digits, and the symbols Yahoo uses (., -, ^, =). */
export const tickerSchema = z
  .string()
  .min(1)
  .max(20)
  .regex(/^[A-Za-z0-9.^=\-]+$/, 'Invalid ticker format');

export const snapshotRequestSchema = z.object({
  userId: z.string().min(1),
  year: z.number().int().min(2000).max(2100).optional(),
  month: z.number().int().min(1).max(12).optional(),
  cronSecret: z.string().optional(),
});

/** Covers the server-relevant subset of DividendFormData fields. */
export const dividendDataSchema = z.object({
  assetId: z.string().min(1),
  // Dates arrive as ISO strings in JSON; coerce to Date objects.
  exDate: z.coerce.date(),
  paymentDate: z.coerce.date(),
  dividendPerShare: z.number().finite(),
  quantity: z.number().finite(),
  grossAmount: z.number().finite(),
  taxAmount: z.number().finite(),
  netAmount: z.number().finite(),
  currency: z.string().min(1).max(10),
  dividendType: z.enum([
    'ordinary',
    'extraordinary',
    'interim',
    'final',
    'coupon',
    'finalPremium',
  ]),
  notes: z.string().optional(),
  isAutoGenerated: z.boolean(),
  // Optional ISIN present on some dividend payloads (bond coupons); validate if provided.
  assetIsin: isinSchema.optional(),
  // Server-set cost basis snapshot — validated if present in the payload.
  costPerShare: z.number().finite().optional(),
});

/**
 * Parse helper: runs safeParse and returns either the typed data or a
 * ready-to-return 400 NextResponse with flattened zod error details.
 */
export function parseOr400<T>(
  schema: z.ZodType<T>,
  data: unknown
): { ok: true; data: T } | { ok: false; response: NextResponse } {
  const result = schema.safeParse(data);
  if (result.success) {
    return { ok: true, data: result.data };
  }
  return {
    ok: false,
    response: NextResponse.json(
      { error: 'Invalid request', details: result.error.flatten() },
      { status: 400 }
    ),
  };
}
