import { NextRequest, NextResponse } from 'next/server';
import {
  getAllDividends,
  getDividendsByAsset,
  getDividendsByDateRange,
} from '@/lib/services/dividendService';
import { adminDb } from '@/lib/firebase/admin';
import { DividendFormData } from '@/types/dividend';
import { Asset } from '@/types/assets';
import {
  assertSameUser,
  getApiAuthErrorResponse,
  requireFirebaseAuth,
} from '@/lib/server/apiAuth';
import { createDividendWithOptionalExpense } from '@/lib/server/dividendUseCase';
import { dividendDataSchema, parseOr400 } from '@/lib/server/validation';

/**
 * GET /api/dividends
 *
 * Flexible dividend query endpoint with multiple filter modes
 *
 * Query Modes (mutually exclusive):
 *   1. By asset:     ?userId=X&assetId=Y
 *   2. By date:      ?userId=X&startDate=2024-01-01&endDate=2024-12-31
 *   3. All user:     ?userId=X
 *
 * Query Parameters:
 *   @param userId - Required. User ID for security filtering
 *   @param assetId - Optional. Returns dividends for specific asset
 *   @param startDate - Optional. ISO date string (requires endDate)
 *   @param endDate - Optional. ISO date string (requires startDate)
 *
 * Response:
 *   {
 *     success: boolean,
 *     dividends: Dividend[],
 *     count: number
 *   }
 *
 * Security: Uses Admin SDK - must verify userId ownership at call site
 */
export async function GET(request: NextRequest) {
  try {
    const decodedToken = await requireFirebaseAuth(request);
    const searchParams = request.nextUrl.searchParams;
    const userId = searchParams.get('userId');
    const assetId = searchParams.get('assetId');
    const startDateStr = searchParams.get('startDate');
    const endDateStr = searchParams.get('endDate');

    assertSameUser(decodedToken, userId);
    const authenticatedUserId = userId as string;

    let dividends;

    // Filter by asset if provided
    if (assetId) {
      dividends = await getDividendsByAsset(authenticatedUserId, assetId);
    }
    // Filter by date range if provided
    else if (startDateStr && endDateStr) {
      const startDate = new Date(startDateStr);
      const endDate = new Date(endDateStr);

      if (isNaN(startDate.getTime()) || isNaN(endDate.getTime())) {
        return NextResponse.json(
          { error: 'Invalid date format' },
          { status: 400 }
        );
      }

      dividends = await getDividendsByDateRange(authenticatedUserId, startDate, endDate);
    }
    // Otherwise, get all dividends
    else {
      dividends = await getAllDividends(authenticatedUserId);
    }

    return NextResponse.json({
      success: true,
      dividends,
      count: dividends.length,
    });
  } catch (error) {
    const authErrorResponse = getApiAuthErrorResponse(error);
    if (authErrorResponse) {
      return authErrorResponse;
    }

    console.error('Error fetching dividends:', error);
    return NextResponse.json(
      { error: 'Failed to fetch dividends', details: (error as Error).message },
      { status: 500 }
    );
  }
}

/**
 * POST /api/dividends
 *
 * Create manual dividend entry with optional automatic expense creation
 *
 * Request Body:
 *   {
 *     userId: string,
 *     dividendData: DividendFormData {
 *       assetId: string,
 *       exDate: Date,
 *       paymentDate: Date,
 *       dividendPerShare: number,
 *       quantity: number,
 *       grossAmount: number,
 *       taxAmount: number,
 *       netAmount: number,
 *       currency: string,
 *       dividendType: string,
 *       notes?: string
 *     }
 *   }
 *
 * Automatic Expense Creation:
 *   If paymentDate <= today AND user has dividendIncomeCategoryId configured:
 *     - Creates linked expense in cashflow
 *     - Uses EUR-converted amount if dividend.currency !== 'EUR'
 *     - Sets dividend.expenseId to link the records
 *
 * Response:
 *   {
 *     success: boolean,
 *     id: string,               // Created dividend ID
 *     expenseId?: string,       // Created expense ID (if applicable)
 *     message: string
 *   }
 *
 * Related:
 *   - dividends/scrape/route.ts: Automated scraping (isAutoGenerated=true)
 *   - cron/daily-dividend-processing/route.ts: Scheduled processing
 *   - dividendIncomeService.ts: Expense creation logic
 */
export async function POST(request: NextRequest) {
  try {
    const decodedToken = await requireFirebaseAuth(request);
    const body = await request.json();

    if (!body.userId || !body.dividendData) {
      return NextResponse.json(
        { error: 'userId and dividendData are required' },
        { status: 400 }
      );
    }

    const userId = body.userId as string;
    assertSameUser(decodedToken, userId);

    const dividendResult = parseOr400(dividendDataSchema, body.dividendData);
    if (!dividendResult.ok) return dividendResult.response;
    const dividendData = dividendResult.data as DividendFormData;

    // Fetch asset to get ticker, name, ISIN, and verify ownership
    const assetDoc = await adminDb
      .collection('assets')
      .doc(dividendData.assetId)
      .get();

    if (!assetDoc.exists) {
      return NextResponse.json({ error: 'Asset not found' }, { status: 404 });
    }

    const asset = { ...(assetDoc.data() as Asset), id: assetDoc.id };

    // Security: Admin SDK bypasses Firestore rules — manual ownership check required
    if (asset.userId !== userId) {
      return NextResponse.json({ error: 'Asset does not belong to user' }, { status: 403 });
    }

    const result = await createDividendWithOptionalExpense(userId, dividendData, asset);

    if (result.skipped) {
      return NextResponse.json({ success: true, message: result.reason });
    }

    return NextResponse.json({
      success: true,
      id: result.dividendId,
      expenseId: result.expenseId,
      message: 'Dividend created successfully',
    });
  } catch (error) {
    const authErrorResponse = getApiAuthErrorResponse(error);
    if (authErrorResponse) {
      return authErrorResponse;
    }

    console.error('Error creating dividend:', error);
    return NextResponse.json(
      { error: 'Failed to create dividend', details: (error as Error).message },
      { status: 500 }
    );
  }
}
