import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('server-only', () => ({}));
vi.mock('@/lib/firebase/config', () => ({ auth: { currentUser: null }, db: {} }));

const {
  createDividendMock,
  deleteUpcomingCouponsForAssetMock,
  deleteUpcomingFinalPremiumForAssetMock,
  getDividendByIdMock,
  createExpenseFromDividendMock,
  settingsDocGetMock,
  categoryDocGetMock,
} = vi.hoisted(() => ({
  createDividendMock: vi.fn(),
  deleteUpcomingCouponsForAssetMock: vi.fn(),
  deleteUpcomingFinalPremiumForAssetMock: vi.fn(),
  getDividendByIdMock: vi.fn(),
  createExpenseFromDividendMock: vi.fn(),
  settingsDocGetMock: vi.fn(),
  categoryDocGetMock: vi.fn(),
}));

vi.mock('@/lib/firebase/admin', () => ({
  adminDb: {
    collection: vi.fn((name: string) => {
      if (name === 'assetAllocationTargets') {
        return { doc: vi.fn(() => ({ get: settingsDocGetMock })) };
      }
      if (name === 'expenseCategories') {
        return { doc: vi.fn(() => ({ get: categoryDocGetMock })) };
      }
      throw new Error(`Unexpected collection: ${name}`);
    }),
  },
}));

vi.mock('@/lib/services/dividendService', () => ({
  createDividend: createDividendMock,
  deleteUpcomingCouponsForAsset: deleteUpcomingCouponsForAssetMock,
  deleteUpcomingFinalPremiumForAsset: deleteUpcomingFinalPremiumForAssetMock,
  getDividendById: getDividendByIdMock,
}));

vi.mock('@/lib/services/dividendIncomeService', () => ({
  createExpenseFromDividend: createExpenseFromDividendMock,
}));

import { createDividendWithOptionalExpense } from '@/lib/server/dividendUseCase';
import { DividendFormData } from '@/types/dividend';
import { Asset } from '@/types/assets';

const baseAsset: Asset & { id: string } = {
  id: 'asset-1',
  userId: 'user-1',
  ticker: 'ENI',
  name: 'Eni SpA',
  isin: 'IT0003132476',
  assetClass: 'equity',
  type: 'stock',
  quantity: 100,
  currentPrice: 14.5,
  averageCost: 12,
  currency: 'EUR',
  isLiquid: true,
  includeInHistoryTables: true,
} as any;

function makeFormData(overrides: Partial<DividendFormData> = {}): DividendFormData {
  return {
    assetId: 'asset-1',
    exDate: new Date('2024-01-10'),
    paymentDate: new Date('2024-01-15'),
    dividendPerShare: 0.5,
    quantity: 100,
    grossAmount: 50,
    taxAmount: 13,
    netAmount: 37,
    currency: 'EUR',
    dividendType: 'ordinary',
    isAutoGenerated: false,
    ...overrides,
  };
}

describe('createDividendWithOptionalExpense', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    createDividendMock.mockResolvedValue('div-123');
  });

  it('creates dividend and expense when paymentDate is in the past and category is configured', async () => {
    // paymentDate as string (simulates JSON deserialization from client)
    const pastDate = '2020-06-01T00:00:00.000Z' as unknown as Date;
    const formData = makeFormData({ paymentDate: pastDate });

    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({
        dividendIncomeCategoryId: 'cat-1',
        dividendIncomeSubCategoryId: 'sub-1',
      }),
    });
    categoryDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({
        name: 'Dividendi',
        subCategories: [{ id: 'sub-1', name: 'Azioni' }],
      }),
    });
    getDividendByIdMock.mockResolvedValue({ id: 'div-123', netAmount: 37, currency: 'EUR' });
    createExpenseFromDividendMock.mockResolvedValue('expense-456');

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: 'expense-456' });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(createExpenseFromDividendMock).toHaveBeenCalledOnce();
  });

  it('does not create an expense for an auto-generated coupon even when paymentDate is today', async () => {
    // Regression: an auto-generated coupon whose next payment date is today must
    // NOT produce an immediate cashflow expense at asset-save time. The daily cron
    // is the single source that creates the expense on payment date.
    const today = new Date();
    const formData = makeFormData({
      dividendType: 'coupon',
      isAutoGenerated: true,
      paymentDate: today,
    });

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(settingsDocGetMock).not.toHaveBeenCalled();
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
  });

  it('creates dividend without expense when paymentDate is in the future', async () => {
    const futureDate = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30); // 30 days ahead
    const formData = makeFormData({ paymentDate: futureDate });

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
    expect(createDividendMock).toHaveBeenCalledOnce();
    expect(settingsDocGetMock).not.toHaveBeenCalled();
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
  });

  it('creates dividend without expense when dividendIncomeCategoryId is not configured', async () => {
    const pastDate = new Date('2020-06-01');
    const formData = makeFormData({ paymentDate: pastDate });

    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({}), // no dividendIncomeCategoryId
    });

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
    expect(createExpenseFromDividendMock).not.toHaveBeenCalled();
  });

  it('returns skipped for auto-generated coupon with quantity 0 (asset sold)', async () => {
    const formData = makeFormData({
      dividendType: 'coupon',
      isAutoGenerated: true,
      quantity: 0,
    });

    deleteUpcomingCouponsForAssetMock.mockResolvedValue(undefined);

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: true, reason: expect.stringContaining('asset sold') });
    expect(deleteUpcomingCouponsForAssetMock).toHaveBeenCalledWith('user-1', 'asset-1');
    expect(createDividendMock).not.toHaveBeenCalled();
  });

  it('returns skipped for auto-generated finalPremium with quantity 0 (asset sold)', async () => {
    const formData = makeFormData({
      dividendType: 'finalPremium',
      isAutoGenerated: true,
      quantity: 0,
    });

    deleteUpcomingFinalPremiumForAssetMock.mockResolvedValue(undefined);

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    expect(result).toEqual({ skipped: true, reason: expect.stringContaining('asset sold') });
    expect(deleteUpcomingFinalPremiumForAssetMock).toHaveBeenCalledWith('user-1', 'asset-1');
    expect(createDividendMock).not.toHaveBeenCalled();
  });

  it('enriches dividend with costPerShare from asset', async () => {
    const futureDate = new Date(Date.now() + 1000 * 60 * 60 * 24 * 30);
    const formData = makeFormData({ paymentDate: futureDate });

    await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    const enrichedData = createDividendMock.mock.calls[0][1];
    expect(enrichedData.costPerShare).toBe(baseAsset.averageCost);
  });

  it('returns dividendId with no expenseId when expense creation fails (non-fatal)', async () => {
    const pastDate = new Date('2020-06-01');
    const formData = makeFormData({ paymentDate: pastDate });

    settingsDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({ dividendIncomeCategoryId: 'cat-1' }),
    });
    categoryDocGetMock.mockResolvedValue({
      exists: true,
      data: () => ({ name: 'Dividendi', subCategories: [] }),
    });
    getDividendByIdMock.mockResolvedValue({ id: 'div-123' });
    createExpenseFromDividendMock.mockRejectedValue(new Error('Firestore error'));

    const result = await createDividendWithOptionalExpense('user-1', formData, baseAsset);

    // Dividend created; expense failure is non-fatal
    expect(result).toEqual({ skipped: false, dividendId: 'div-123', expenseId: undefined });
  });
});
