import { describe, it, expect } from 'vitest';
import { Dividend } from '@/types/dividend';
import {
  netEur,
  grossEur,
  taxEur,
  isPaid,
  filterPaidByPeriod,
  monthsInWindow,
  computePeriodSummary,
  computeNetComparison,
  computeUpcomingNet,
  rankPayers,
  buildMonthlyNetSeries,
  buildYearlySeries,
  computeReliability,
  periodToDateBounds,
  MAX_RANKED_PAYERS,
} from '@/lib/utils/dividendAnalytics';

// --- Fixtures ---------------------------------------------------------------

// Minimal dividend factory. Payment date is the axis everything is grouped by; amounts
// default so that net = gross - tax. Dates are set at noon to stay clear of timezone
// boundaries in tests.
function makeDividend(overrides: Partial<Dividend> & { paymentDate: Date }): Dividend {
  const gross = overrides.grossAmount ?? 100;
  const tax = overrides.taxAmount ?? 26;
  return {
    id: Math.random().toString(36).slice(2),
    userId: 'u1',
    assetId: 'a1',
    assetTicker: 'AAA',
    assetName: 'Asset A',
    exDate: overrides.exDate ?? overrides.paymentDate,
    dividendPerShare: 1,
    quantity: 100,
    grossAmount: gross,
    taxAmount: tax,
    netAmount: gross - tax,
    currency: 'EUR',
    dividendType: 'ordinary',
    isAutoGenerated: false,
    createdAt: new Date('2020-01-01'),
    updatedAt: new Date('2020-01-01'),
    ...overrides,
  };
}

const NOW = new Date('2026-06-15T12:00:00');

describe('money helpers', () => {
  it('prefers the converted EUR fields when present', () => {
    const d = makeDividend({
      paymentDate: new Date('2026-06-01T12:00:00'),
      grossAmount: 100,
      taxAmount: 15,
      netAmount: 85,
      grossAmountEur: 92,
      taxAmountEur: 13,
      netAmountEur: 79,
    });
    expect(grossEur(d)).toBe(92);
    expect(taxEur(d)).toBe(13);
    expect(netEur(d)).toBe(79);
  });

  it('falls back to native amounts for EUR/legacy records', () => {
    const d = makeDividend({ paymentDate: new Date('2026-06-01T12:00:00') });
    expect(netEur(d)).toBe(74); // 100 - 26
  });
});

describe('isPaid', () => {
  it('treats a payment on or before now as paid', () => {
    expect(isPaid(makeDividend({ paymentDate: new Date('2026-06-15T12:00:00') }), NOW)).toBe(true);
    expect(isPaid(makeDividend({ paymentDate: new Date('2026-06-10T12:00:00') }), NOW)).toBe(true);
  });

  it('treats a future payment as not paid', () => {
    expect(isPaid(makeDividend({ paymentDate: new Date('2026-07-01T12:00:00') }), NOW)).toBe(false);
  });
});

describe('filterPaidByPeriod', () => {
  const dividends = [
    makeDividend({ paymentDate: new Date('2026-06-05T12:00:00') }), // this month
    makeDividend({ paymentDate: new Date('2026-03-05T12:00:00') }), // this year, not month
    makeDividend({ paymentDate: new Date('2025-09-05T12:00:00') }), // within rolling12
    makeDividend({ paymentDate: new Date('2024-01-05T12:00:00') }), // old
    makeDividend({ paymentDate: new Date('2026-12-05T12:00:00') }), // future → excluded everywhere
  ];

  it('month keeps only the current calendar month', () => {
    expect(filterPaidByPeriod(dividends, 'month', NOW)).toHaveLength(1);
  });

  it('year keeps the current calendar year', () => {
    expect(filterPaidByPeriod(dividends, 'year', NOW)).toHaveLength(2);
  });

  it('rolling12 keeps the trailing 12 months', () => {
    // June 2026, March 2026, September 2025 are all within the last 12 months.
    expect(filterPaidByPeriod(dividends, 'rolling12', NOW)).toHaveLength(3);
  });

  it('all keeps every paid dividend (future excluded)', () => {
    expect(filterPaidByPeriod(dividends, 'all', NOW)).toHaveLength(4);
  });
});

describe('monthsInWindow', () => {
  it('returns 1 for month and 12 for rolling12', () => {
    expect(monthsInWindow('month', [], NOW)).toBe(1);
    expect(monthsInWindow('rolling12', [], NOW)).toBe(12);
  });

  it('returns elapsed months for year', () => {
    expect(monthsInWindow('year', [], NOW)).toBe(6); // June
  });

  it('spans first paid month → now for all', () => {
    const paid = [
      makeDividend({ paymentDate: new Date('2026-01-15T12:00:00') }),
      makeDividend({ paymentDate: new Date('2026-06-15T12:00:00') }),
    ];
    expect(monthsInWindow('all', paid, NOW)).toBe(6); // Jan..Jun inclusive
  });
});

describe('computePeriodSummary', () => {
  it('sums net/gross/tax and computes a true monthly average', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-02-15T12:00:00'), grossAmount: 120, taxAmount: 20, netAmount: 100 }),
      makeDividend({ paymentDate: new Date('2026-05-15T12:00:00'), grossAmount: 240, taxAmount: 40, netAmount: 200 }),
    ];
    const summary = computePeriodSummary(dividends, 'year', NOW);
    expect(summary.net).toBe(300);
    expect(summary.gross).toBe(360);
    expect(summary.tax).toBe(60);
    expect(summary.count).toBe(2);
    // 300 net over 6 elapsed months
    expect(summary.averageMonthlyNet).toBe(50);
  });
});

describe('computeNetComparison', () => {
  it('computes a signed delta vs the previous year', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), netAmount: 150, grossAmount: 150, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2025-03-15T12:00:00'), netAmount: 100, grossAmount: 100, taxAmount: 0 }),
    ];
    const cmp = computeNetComparison(dividends, 'year', NOW);
    expect(cmp.current).toBe(150);
    expect(cmp.previous).toBe(100);
    expect(cmp.deltaPct).toBeCloseTo(0.5);
  });

  it('returns null delta for all (no predecessor)', () => {
    const cmp = computeNetComparison([], 'all', NOW);
    expect(cmp.deltaPct).toBeNull();
  });

  it('returns null delta when the previous window had no income', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), netAmount: 150, grossAmount: 150, taxAmount: 0 }),
    ];
    expect(computeNetComparison(dividends, 'year', NOW).deltaPct).toBeNull();
  });
});

describe('computeUpcomingNet', () => {
  it('sums only future-dated payments', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-06-01T12:00:00'), netAmount: 50, grossAmount: 50, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-07-01T12:00:00'), netAmount: 80, grossAmount: 80, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-08-01T12:00:00'), netAmount: 20, grossAmount: 20, taxAmount: 0 }),
    ];
    expect(computeUpcomingNet(dividends, NOW)).toBe(100);
  });
});

describe('rankPayers', () => {
  it('ranks payers by net income descending and aggregates per asset', () => {
    const dividends = [
      makeDividend({ assetId: 'a', assetTicker: 'A', paymentDate: new Date('2026-02-15T12:00:00'), netAmount: 30, grossAmount: 30, taxAmount: 0 }),
      makeDividend({ assetId: 'a', assetTicker: 'A', paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 30, grossAmount: 30, taxAmount: 0 }),
      makeDividend({ assetId: 'b', assetTicker: 'B', paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 100, grossAmount: 100, taxAmount: 0 }),
    ];
    const ranked = rankPayers(dividends, 'year', NOW);
    expect(ranked.map((r) => r.assetTicker)).toEqual(['B', 'A']);
    expect(ranked[1]).toMatchObject({ net: 60, count: 2 });
  });

  it('collapses payers past the cap into a single "Altri" row', () => {
    const dividends = Array.from({ length: MAX_RANKED_PAYERS + 3 }, (_, i) =>
      makeDividend({
        assetId: `a${i}`,
        assetTicker: `A${i}`,
        paymentDate: new Date('2026-05-15T12:00:00'),
        netAmount: 100 - i, // strictly descending so the tail is the smallest
        grossAmount: 100 - i,
        taxAmount: 0,
      }),
    );
    const ranked = rankPayers(dividends, 'year', NOW);
    expect(ranked).toHaveLength(MAX_RANKED_PAYERS + 1);
    expect(ranked[ranked.length - 1].assetTicker).toBe('Altri');
    expect(ranked[ranked.length - 1].count).toBe(3);
  });
});

describe('buildMonthlyNetSeries', () => {
  it('produces a gap-free month axis with zeros for empty months', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-01-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-04-15T12:00:00'), netAmount: 40, grossAmount: 40, taxAmount: 0 }),
    ];
    const series = buildMonthlyNetSeries(dividends, NOW);
    expect(series.map((p) => p.net)).toEqual([10, 0, 0, 40]); // Jan, Feb, Mar, Apr
  });

  it('keeps only the most recent N months when maxMonths is given', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2025-01-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 40, grossAmount: 40, taxAmount: 0 }),
    ];
    const series = buildMonthlyNetSeries(dividends, NOW, 3);
    expect(series).toHaveLength(3);
    expect(series[series.length - 1].net).toBe(40);
  });

  it('returns an empty series when there are no paid dividends', () => {
    expect(buildMonthlyNetSeries([], NOW)).toEqual([]);
  });
});

describe('buildYearlySeries', () => {
  it('groups gross/tax/net by payment year, ascending', () => {
    const dividends = [
      makeDividend({ paymentDate: new Date('2025-03-15T12:00:00'), grossAmount: 100, taxAmount: 20, netAmount: 80 }),
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), grossAmount: 200, taxAmount: 40, netAmount: 160 }),
    ];
    const series = buildYearlySeries(dividends, NOW);
    expect(series.map((p) => p.year)).toEqual([2025, 2026]);
    expect(series[1]).toMatchObject({ gross: 200, tax: 40, net: 160 });
  });
});

describe('computeReliability', () => {
  it('measures income coverage across the window', () => {
    // 3 distinct months with income out of 6 elapsed this year → 50% coverage.
    const dividends = [
      makeDividend({ paymentDate: new Date('2026-01-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-03-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
      makeDividend({ paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 10, grossAmount: 10, taxAmount: 0 }),
    ];
    const r = computeReliability(dividends, 'year', NOW);
    expect(r.monthsWithIncome).toBe(3);
    expect(r.monthsInWindow).toBe(6);
    expect(r.coveragePct).toBeCloseTo(0.5);
  });

  it('measures payer concentration (HHI and top share)', () => {
    const dividends = [
      makeDividend({ assetId: 'a', assetTicker: 'A', paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 75, grossAmount: 75, taxAmount: 0 }),
      makeDividend({ assetId: 'b', assetTicker: 'B', paymentDate: new Date('2026-05-15T12:00:00'), netAmount: 25, grossAmount: 25, taxAmount: 0 }),
    ];
    const r = computeReliability(dividends, 'year', NOW);
    expect(r.topPayerSharePct).toBeCloseTo(0.75);
    expect(r.topPayerTicker).toBe('A');
    // HHI = 0.75^2 + 0.25^2 = 0.625
    expect(r.concentrationHhi).toBeCloseTo(0.625);
    expect(r.payerCount).toBe(2);
  });

  it('reports zero concentration when there is no income', () => {
    const r = computeReliability([], 'year', NOW);
    expect(r.topPayerSharePct).toBe(0);
    expect(r.concentrationHhi).toBe(0);
    expect(r.topPayerTicker).toBeNull();
  });
});

describe('periodToDateBounds', () => {
  it('returns no bounds for all', () => {
    expect(periodToDateBounds('all', NOW)).toEqual({});
  });

  it('bounds the current month from the 1st to now', () => {
    const { startDate, endDate } = periodToDateBounds('month', NOW);
    expect(startDate).toEqual(new Date(2026, 5, 1, 0, 0, 0));
    expect(endDate).toBe(NOW);
  });

  it('bounds the year from Jan 1 to now', () => {
    const { startDate } = periodToDateBounds('year', NOW);
    expect(startDate).toEqual(new Date(2026, 0, 1, 0, 0, 0));
  });

  it('bounds rolling12 to 11 months back', () => {
    const { startDate } = periodToDateBounds('rolling12', NOW);
    expect(startDate).toEqual(new Date(2025, 6, 1, 0, 0, 0)); // July 2025
  });
});
