import { describe, it, expect, vi } from 'vitest';

vi.mock('server-only', () => ({}));

import {
  isinSchema,
  tickerSchema,
  snapshotRequestSchema,
  dividendDataSchema,
  parseOr400,
} from '@/lib/server/validation';

describe('isinSchema', () => {
  it.each([
    'IT0005672024',
    'US0378331005',
    'IE00B4L5Y983',
    'LU0274208692',
  ])('accepts valid ISIN %s', (isin) => {
    expect(isinSchema.safeParse(isin).success).toBe(true);
  });

  it.each([
    ['too short', 'IT000'],
    ['too long', 'IT00567202412345'],
    ['lowercase', 'it0005672024'],
    ['query injection', 'IT000&lang=en&x='],
    ['path traversal', 'IT0005/../secret'],
    ['empty string', ''],
  ])('rejects %s', (_, value) => {
    expect(isinSchema.safeParse(value).success).toBe(false);
  });
});

describe('tickerSchema', () => {
  it.each([
    'AAPL',
    'VWCE.L',
    'BRK-B',
    'SP500^',
    'SWDA.L',
    'CSSPX',
  ])('accepts valid ticker %s', (ticker) => {
    expect(tickerSchema.safeParse(ticker).success).toBe(true);
  });

  it.each([
    ['empty string', ''],
    ['too long', 'AAAAAAAAAAAAAAAAAAAAAA'],
    ['spaces', 'VOO ETF'],
    ['semicolon injection', 'AAPL;DROP'],
  ])('rejects %s', (_, value) => {
    expect(tickerSchema.safeParse(value).success).toBe(false);
  });
});

describe('snapshotRequestSchema', () => {
  it('accepts a minimal valid body', () => {
    expect(
      snapshotRequestSchema.safeParse({ userId: 'user-1' }).success
    ).toBe(true);
  });

  it('accepts a full valid body', () => {
    expect(
      snapshotRequestSchema.safeParse({
        userId: 'user-1',
        year: 2025,
        month: 6,
        cronSecret: 'secret',
      }).success
    ).toBe(true);
  });

  it('rejects empty userId', () => {
    expect(snapshotRequestSchema.safeParse({ userId: '' }).success).toBe(false);
  });

  it.each([
    ['year too low', { userId: 'u', year: 1999 }],
    ['year too high', { userId: 'u', year: 2101 }],
    ['month 0', { userId: 'u', month: 0 }],
    ['month 13', { userId: 'u', month: 13 }],
    ['fractional month', { userId: 'u', month: 1.5 }],
  ])('rejects %s', (_, body) => {
    expect(snapshotRequestSchema.safeParse(body).success).toBe(false);
  });
});

describe('dividendDataSchema', () => {
  const basePayload = {
    assetId: 'asset-1',
    exDate: '2024-06-15T00:00:00.000Z',
    paymentDate: '2024-06-20T00:00:00.000Z',
    dividendPerShare: 0.5,
    quantity: 100,
    grossAmount: 50,
    taxAmount: 13,
    netAmount: 37,
    currency: 'EUR',
    dividendType: 'ordinary',
    isAutoGenerated: false,
  };

  it('accepts a valid dividend payload', () => {
    expect(dividendDataSchema.safeParse(basePayload).success).toBe(true);
  });

  it('coerces ISO date strings to Date objects', () => {
    const result = dividendDataSchema.safeParse(basePayload);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.exDate).toBeInstanceOf(Date);
      expect(result.data.paymentDate).toBeInstanceOf(Date);
    }
  });

  it('rejects empty assetId', () => {
    expect(dividendDataSchema.safeParse({ ...basePayload, assetId: '' }).success).toBe(false);
  });

  it.each([
    ['grossAmount', Infinity],
    ['taxAmount', NaN],
    ['netAmount', Infinity],
    ['dividendPerShare', Infinity],
  ])('rejects non-finite %s', (field, value) => {
    expect(dividendDataSchema.safeParse({ ...basePayload, [field]: value }).success).toBe(false);
  });

  it('rejects unknown dividendType', () => {
    expect(
      dividendDataSchema.safeParse({ ...basePayload, dividendType: 'special' }).success
    ).toBe(false);
  });

  it('accepts all valid dividendType values', () => {
    const types = ['ordinary', 'extraordinary', 'interim', 'final', 'coupon', 'finalPremium'];
    for (const t of types) {
      expect(
        dividendDataSchema.safeParse({ ...basePayload, dividendType: t }).success
      ).toBe(true);
    }
  });

  it('validates assetIsin when provided', () => {
    expect(
      dividendDataSchema.safeParse({ ...basePayload, assetIsin: 'IT0005672024' }).success
    ).toBe(true);
    expect(
      dividendDataSchema.safeParse({ ...basePayload, assetIsin: 'INVALID' }).success
    ).toBe(false);
  });

  it('accepts payload without optional assetIsin', () => {
    expect(dividendDataSchema.safeParse(basePayload).success).toBe(true);
  });
});

describe('parseOr400', () => {
  it('returns ok:true with typed data for valid input', () => {
    const result = parseOr400(isinSchema, 'IT0005672024');
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.data).toBe('IT0005672024');
    }
  });

  it('returns ok:false with a NextResponse 400 for invalid input', async () => {
    const result = parseOr400(isinSchema, 'INVALID');
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.response.status).toBe(400);
      const body = await result.response.json();
      expect(body).toHaveProperty('error');
      expect(body).toHaveProperty('details');
    }
  });

  it('includes flattened field errors in the 400 response', async () => {
    const result = parseOr400(snapshotRequestSchema, { month: 13 });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      const body = await result.response.json();
      // userId is missing, month is out of range — both should appear in fieldErrors
      expect(body.details.fieldErrors).toBeDefined();
    }
  });
});
